import math
p=int(input("calc? (1/0)"))
while p==1:
  print("QUAD 2.1(fix)")
  a=int(input("a = "))
  b=int(input("b = "))
  c=int(input("c = "))
  de=b**2-4*a*c
  print(" ")
  print("Delta=")
  print(de)
  print("      ")
  if de<0:
    print("Unsolvable")
    p=int(input("calc again?"))
  if de==0:
    sol1=(-b)/(2*a)
    sol11=(-b)
    sol12=(2*a)
    print("Solvable 1sol")
    print(" ")
    print(sol11)
    print("------")
    print(sol12)
    print(" ")
    print(sol1)
    p=int(input("calc again?"))
  if de>0:
    s=math.sqrt(de)
    sol1=(-b+s)/(2*a)
    sol11=(-b+s)
    sol2=(-b-s)/(2*a)
    sol22=(-b-s)
    p=2*a
    print("Solvable 2sol")
    print(sol11)
    print("------")
    print(p)
    print("      ")
    print(sol1)
    print("      ")
    print(sol22)
    print("------")
    print(p)
    print("      ")
    print(sol2)
    p=int(input("calc again?"))